# Generated by Django 4.1.2 on 2022-10-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('email', models.CharField(max_length=120, verbose_name='email')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
            ],
        ),
    ]
